letters_numbers_capletters_asciibits = {
    'a': 'alpha',
    'b': 'bravo',
    'c': 'charlie',
    'd': 'delta',
    'e': 'echo',
    'f': 'foxtrot',
    'g': 'gulf',
    'h': 'hotel',
    'i': 'india',
    'j': 'juliet',
    'k': 'kilo',
    'l': 'lima',
    'm': 'mike',
    'n': 'november',
    'o': 'oscar',
    'p': 'papa',
    'q': 'quebec',
    'r': 'romeo',
    's': 'sierra',
    't': 'tango',
    'u': 'uniform',
    'v': 'victor',
    'w': 'whiskey',
    'x': 'xray',
    'y': 'yankee',
    'z': 'zulu',
    'A': 'alpha-capitalized',
    'B': 'bravo-capitalized',
    'C': 'charlie-capitalized',
    'D': 'delta-capitalized',
    'E': 'echo-capitalized',
    'F': 'foxtrot-capitalized',
    'G': 'gulf-capitalized',
    'H': 'hotel-capitalized',
    'I': 'india-capitalized',
    'J': 'juliet-capitalized',
    'K': 'kilo-capitalized',
    'L': 'lima-capitalized',
    'M': 'mike-capitalized',
    'N': 'november-capitalized',
    'O': 'oscar-capitalized',
    'P': 'papa-capitalized',
    'Q': 'quebec-capitalized',
    'R': 'romeo-capitalized',
    'S': 'sierra-capitalized',
    'T': 'tango-capitalized',
    'U': 'uniform-capitalized',
    'V': 'victor-capitalized',
    'W': 'whiskey-capitalized',
    'X': 'xray-capitalized',
    'Y': 'yankee-capitalized',
    'Z': 'zulu-capitalized',
    '0': 'zero',
    '1': 'one',
    '2': 'two',
    '3': 'three',
    '4': 'four',
    '5': 'five',
    '6': 'six',
    '7': 'seven',
    '8': 'eight',
    '9': 'niner',
    '~': 'tilde',
    '!': 'exclamation',
    '@': 'atsymbol',
    '#': 'numbersign',
    '$': 'dollarsign',
    '%': 'percent',
    '^': 'caret',
    '&': 'andsign',
    '*': 'asterisk',
    '(': 'openparenthesis',
    ')': 'closedparenthesis',
    '-': 'dash',
    '=': 'equal',
    '+': 'plus',
    '?': 'questionmark',
    '.': 'period',
    '/': 'forwardslash',
    '|': 'pipe',
    '<': 'lessthan',
    '>': 'greaterthan',
    ':': 'colon',
    ';': 'semicolon',
    ',': 'comma',
    '_': 'underscore',
    ' ': '←→',
    '\\': 'backslash',
}
while True:
    try:
        user_input = input("\nType a password, Ctrl+C to stop: ")
        print("\nRemove delimiting combined up & down arrows, then add the military words side by side, that is your passwd")
        print("Your military encoded passwd below =)")
        for x in user_input:
            if x in letters_numbers_capletters_asciibits:
                print(letters_numbers_capletters_asciibits[x], end="↑↓")
            else:
                print(f"[Unknown Character: {x}]", end=" ")
        print(" ")
    except KeyboardInterrupt:
        print("\nStopped")
        break